#!/bin/bash

# Create the entire file via echo or create it beforehand?
export AWS_REGION="us-west-2"
export AWS_CONFIG_FILE=aws-config
echo "[profile prod]" >> aws-config
echo "region=us-west-2" >> caws-onfig
echo "output=json" >> aws-config
echo "credential_source=EcsContainer" >> aws-config
echo "role_arn=$CLOUDMAPPER_PROD_ROLE_ARN" >> aws-config
echo "" >> aws-config

echo "[profile dev]" >> aws-config
echo "region=us-west-2" >> caws-onfig
echo "output=json" >> aws-config
echo "credential_source=EcsContainer" >> aws-config
echo "role_arn=$CLOUDMAPPER_DEV_ROLE_ARN" >> aws-config
echo "" >> aws-config

echo "[profile solutions-external]" >> aws-config
echo "region=us-west-2" >> caws-onfig
echo "output=json" >> aws-config
echo "credential_source=EcsContainer" >> aws-config
echo "role_arn=$CLOUDMAPPER_SOL_EXT_ROLE_ARN" >> aws-config
echo "" >> aws-config

# Configure config.json for CloudMapper
python cloudmapper.py configure add-account --config-file config.json --name prod --id $PROD_ID
python cloudmapper.py configure add-account --config-file config.json --name dev --id $DEV_ID
python cloudmapper.py configure add-account --config-file config.json --name solutions-external --id $SOL_EXT_ID

# Run CloudMapper
python cloudmapper.py collect --account prod --profile prod --regions us-west-2 --clean
python cloudmapper.py stats --accounts prod --stats_all_resources --no_output_image \
    > prod-stats-$( printf '%(%Y%m%d)T\n' -1 ).txt

python cloudmapper.py collect --account dev --profile dev --regions us-west-2 --clean
python cloudmapper.py stats --accounts dev --stats_all_resources --no_output_image \
    > dev-stats-$( printf '%(%Y%m%d)T\n' -1 ).txt

python cloudmapper.py collect --account solutions-external --profile solutions-external --regions us-west-2 --clean
python cloudmapper.py stats --accounts solutions-external --stats_all_resources --no_output_image \
    > solutions-external-stats-$( printf '%(%Y%m%d)T\n' -1 ).txt

# Output stats results to S3
aws s3 cp prod-stats-$( printf '%(%Y%m%d)T\n' -1 ).txt s3://$S3_BUCKET/$S3_BUCKET_CLOUDMAPPER_LOG_FOLDER
aws s3 cp dev-stats-$( printf '%(%Y%m%d)T\n' -1 ).txt s3://$S3_BUCKET/$S3_BUCKET_CLOUDMAPPER_LOG_FOLDER
aws s3 cp solutions-external-stats-$( printf '%(%Y%m%d)T\n' -1 ).txt s3://$S3_BUCKET/$S3_BUCKET_CLOUDMAPPER_LOG_FOLDER